### ISSUE TITLE
Sadly even with Pull Request #15 your RDE tool does not work - downloads empty .txt files (no comment body) and complains about AttributeError: '<class 'praw.objects.Submission'>' has no attribute 'comments'

### ISSUE THREAD

**Issue by informer2016** [NSchrading/redditDataExtractor#16] opened 2019-01-13 18:58 UTC
@NSchrading  Sadly even with Pull Request #15 your RDE tool does not work - downloads empty .txt files (no comment body) and complains about AttributeError: '<class 'praw.objects.Submission'>' has no attribute 'comments' . Please reply if you still care about your tool, I think I did like 90% of work but got stuck a bit

**Comment by smcnally** [comment] 2019-03-20 23:37
Using the [latest 1.2 release exe.linux-x86_64-3.4 ](https://github.com/NSchrading/redditDataExtractor/releases/tag/1.2) on Ubuntu 18.04 and also getting 0-byte text files. 
JPGs are downloading as-designed. 

In the gui, the only detail is "Error saving submission:"
![image](https://user-images.githubusercontent.com/850878/54725778-97913c00-4b2d-11e9-9fc1-6d8dd381b2ae.png)

In syslog, I see 

> Could not find config file ... 'praw.ini' - 

which is likely the issue. I'll dig in next and report back here.

**Comment by smcnally** [comment] 2019-03-21 00:36
The dev addressed a [related issue in this comment](https://github.com/NSchrading/redditDataExtractor/issues/7#issuecomment-275904658):

>  I suspect the problem is that you are using the new, backwards-incompatible version of PRAW (v4+). When I wrote this, only PRAW v3 was around. Try downgrading to PRAW v3 (I think 3.4.0 or 3.5.0 is the latest). Hopefully that will fix it.

I [replaced PRAW 5.3 with v3.5.0](https://praw.readthedocs.io/en/latest/getting_started/installation.html#installing-older-versions) and redditDataExtractor is Working as Designed. 

The only related entries I see now in syslog are

> PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Thanks for making this tool available, @NSchrading

**Comment by NSchrading** [comment] 2024-12-18 03:20
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.

**Closed as completed by NSchrading** 2024-12-18 03:20 UTC
